#version: "3.7"
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=yp-db

  zookeeper:
    image: kymeric/cp-zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kiwikafka

  kafka:
    image: kymeric/cp-kafka:latest
    depends_on: [zookeeper]
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
      KAFKAJS_NO_PARTITIONER_WARNING: 1
    networks:
      - kiwikafka

  kiwi:
    image: dmwood/kiwi:latest
    ports:
      - '8081:8080'
    environment:
      KAFKA_BASE_CLIENT_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - kiwikafka
  app:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: app-anti-fraud
    restart: always
    ports:
      - 3000:3000
    command: bash -c /usr/src/app/start.sh
    env_file: .env
